debianize

diff --git a/packages/debian/voxinup.init b/packages/debian/voxinup.init
--- a/packages/debian/voxinup.init
+++ b/packages/debian/voxinup.init
@@ -1,12 +1,13 @@
 #!/bin/sh
 # 
+# 
 # voxinup init.d script with LSB support.
 #
 # This file is based on the original work from:
 # Espeakup init.d script with LSB support.
 #
 # Copyright (c) 2007 Javier Fernandez-Sanguino <jfs@debian.org>
-# Copyright (c) 2009 Samuel Thibault <samuel.thibault@ens-lyon.org>
+# Copyright (c) 2009, 2015-2016 Samuel Thibault <samuel.thibault@ens-lyon.org>
 #
 # This is free software; you may redistribute it and/or modify
 # it under the terms of the GNU General Public License as
@@ -31,8 +32,8 @@
 # Should-Stop:
 # Default-Start:     S
 # Default-Stop:
-# Short-Description: Speakup/ibmtts connector
-# Description:       Daemon that makes speakup use the ibmtts
+# Short-Description: Speakup/voxin connector
+# Description:       Daemon that makes speakup use the voxin
 #                    software speech synthesizer
 ### END INIT INFO
 
@@ -43,6 +44,8 @@ NAME=voxinup
 DESC="Speakup/voxin connector"
 LOGDIR=/var/log/voxinup
 
+PIDFILE=/var/run/$NAME.pid
+
 test -x $DAEMON || exit 0
 test -r /dev/softsynth || exit 0
 
@@ -52,12 +55,15 @@ test -r /dev/softsynth || exit 0
 # at /etc/default/$NAME
 DAEMON_OPTS=""          # Additional options given to the server
 
+VOICE=""
+
 DIETIME=10              # Time to wait for the server to die, in seconds
                         # If this value is set too low you might not
                         # let some servers to die gracefully and
                         # 'restart' will not work
 
-#STARTTIME=2             # Time to wait for the server to start, in seconds
+# TODO: Disable by default again, see #775131
+STARTTIME=2             # Time to wait for the server to start, in seconds
                         # If this value is set each time the server is
                         # started (on start or restart) the script will
                         # stall to try to determine if it is running
@@ -66,73 +72,144 @@ DIETIME=10              # Time to wait for the server to die, in seconds
                         # be a false positive (says it did not start
                         # when it actually did)
 
+MAX_NB_OF_RETRIES=5     # If the server does not start after STARTTIME
+                        # a retry is achieved. 
+                        # MAX_NB_OF_RETRIES indicates the maximum number of retries
+
 LOGFILE=$LOGDIR/$NAME.log  # Server logfile
 
 # Include defaults if available
 if [ -f /etc/default/$NAME ] ; then
     . /etc/default/$NAME
+    if [ -n "$ALSA_CARD" ]
+    then
+    	# Wait for detection of the requested alsa card
+	while ! grep -q "$ALSA_CARD" /sys/class/sound/card*/id && [ ! -f "/sys/class/sound/card$ALSA_CARD/id" ]
+	do
+	    sleep 0.1
+	done
+    fi
 fi
+
+[ -z "$VOICE" ] || DAEMON_OPTS="$DAEMON_OPTS -V $VOICE"
 
 set -e
 
-running() {
-    pid=$( pidof /usr/bin/voxinup )
-    return $?
+running_pid() {
+# Check if a given process pid's cmdline matches a given name
+    pid=$1
+    name=$2
+    [ -z "$pid" ] && return 1
+    [ ! -d /proc/$pid ] &&  return 1
+    cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -n 1 |cut -d : -f 1`
+    # Is this the expected server
+    [ "$cmd" != "$name" ] &&  return 1
+    return 0
 }
 
+running() {
+# Check if the process is running looking at /proc
+# (works for all users)
+
+    # No pidfile, probably no daemon present
+    [ ! -f "$PIDFILE" ] && return 1
+    pid=`cat $PIDFILE`
+    running_pid $pid $DAEMON || return 1
+    return 0
+}
 
 start_server() {
     start_daemon $DAEMON $DAEMON_OPTS
 }
 
 stop_server() {
-    pid=$( pidof /usr/bin/voxinup )
-    if [ "$?" != "0" ]; then
-	return 0
-    fi
-    kill -TERM $pid
+    killproc -p $PIDFILE $DAEMON
 }
 
 reload_server() {
-    pid=$( pidof /usr/bin/voxinup )
-    if [ "$?" != "0" ]; then
-	return 0
-    fi
-    kill -HUP $pid
+    [ ! -f "$PIDFILE" ] && return 1
+    pid=pidofproc $PIDFILE # This is the daemon's pid
+    # Send a SIGHUP
+    kill -1 $pid
     return $?
 }
 
 force_stop() {
-    pid=$( pidof /usr/bin/voxinup )
-    if [ "$?" != "0" ]; then
-	return 0
+# Force the process to die killing it manually
+    [ ! -e "$PIDFILE" ] && return
+    if running ; then
+        kill -15 $pid
+        # Is it really dead?
+        sleep "$DIETIME"s
+        if running ; then
+            kill -9 $pid
+            sleep "$DIETIME"s
+            if running ; then
+                echo "Cannot kill $NAME (pid=$pid)!"
+                exit 1
+            fi
+        fi
     fi
-    kill -KILL $pid
+    rm -f $PIDFILE
 }
 
 
 case "$1" in
   start)
         log_daemon_msg "Starting $DESC " "$NAME"
-        if start_server ; then
+        # Check if it's running first
+        if running ;  then
+            log_progress_msg "apparently already running"
             log_end_msg 0
-        else
-            log_end_msg 1
+            exit 0
         fi
+
+	RETRY=0
+	while [ "$RETRY" -lt "$MAX_NB_OF_RETRIES" ]; do
+            if start_server ; then
+		# NOTE: Some servers might die some time after they start,
+		# this code will detect this issue if STARTTIME is set
+		# to a reasonable value
+		[ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time 
+		if  running ;  then
+                    # It's ok, the server started and is running
+		    break
+		else
+                    # It is not running after we did start
+		    RETRY=$(($RETRY+1))
+		fi
+            fi
+	done
+	if [ "$RETRY" -le "$MAX_NB_OF_RETRIES" ]; then
+	    log_end_msg 0
+	else
+	    log_end_msg 1
+	fi	
         ;;
   stop)
         log_daemon_msg "Stopping $DESC" "$NAME"
-        errcode=0
-        stop_server || errcode=$?
-        log_end_msg $errcode
+        if running ; then
+            # Only stop the server if we see it running
+            errcode=0
+            stop_server || errcode=$?
+            log_end_msg $errcode
+        else
+            # If it's not running don't do anything
+            log_progress_msg "apparently not running"
+            log_end_msg 0
+            exit 0
+        fi
         ;;
   force-stop)
         # First try to stop gracefully the program
         $0 stop
-        log_daemon_msg "Stopping (force) $DESC" "$NAME"
-        errcode=0
-        force_stop || errcode=$?
-        log_end_msg $errcode
+        if running; then
+            # If it's still running try to kill it more forcefully
+            log_daemon_msg "Stopping (force) $DESC" "$NAME"
+            errcode=0
+            force_stop || errcode=$?
+            log_end_msg $errcode
+        fi
         ;;
   restart|force-reload)
         log_daemon_msg "Restarting $DESC" "$NAME"
@@ -142,9 +219,11 @@ case "$1" in
         [ -n "$DIETIME" ] && sleep $DIETIME
         start_server || errcode=$?
         [ -n "$STARTTIME" ] && sleep $STARTTIME
+        running || errcode=$?
         log_end_msg $errcode
         ;;
   status)
+
         log_daemon_msg "Checking status of $DESC" "$NAME"
         if running ;  then
             log_progress_msg "running"
